name: Mirror to Bitbucket Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key and set SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: "git@github.com:Qiu-0/Zhangli.git"
          destination-repo: "git@gitee.com:Qiu-0/Zhangli.git"